-- Phase 3: surveys, published versions, public links (QR targets), responses and answers.
--
-- Editing model: a survey's editable content lives in surveys.questions (jsonb draft, validated by
-- the application). Publishing freezes it into an immutable survey_versions row. Customers only
-- ever see a published version, and every response records the version it answered, so later
-- edits never change what old responses mean.
--
-- Definition format (draft questions and version definition.questions):
--   { "id": uuid, "type": "rating"|"nps"|"single_choice"|"multiple_choice"|"text",
--     "required": bool, "role": "csat"|null,
--     "title": {"ar": text, "en": text}, "options": [{"id": uuid, "label": {"ar": text, "en": text}}] }

create type public.survey_status as enum ('draft', 'published', 'paused', 'archived');

create table public.surveys (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations (id) on delete cascade,
  name text not null check (char_length(btrim(name)) between 1 and 120),
  status public.survey_status not null default 'draft',
  default_locale public.app_locale not null default 'ar',
  locales public.app_locale[] not null default '{ar}' check (cardinality(locales) between 1 and 2),
  questions jsonb not null default '[]'::jsonb check (jsonb_typeof(questions) = 'array'),
  thank_you jsonb not null default '{}'::jsonb check (jsonb_typeof(thank_you) = 'object'),
  current_version_id uuid,
  has_unpublished_changes boolean not null default false,
  created_by uuid references auth.users (id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (default_locale = any (locales))
);

create index surveys_organization_id_idx on public.surveys (organization_id);

create table public.survey_versions (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations (id) on delete cascade,
  survey_id uuid not null references public.surveys (id) on delete cascade,
  version integer not null check (version > 0),
  definition jsonb not null,
  published_by uuid references auth.users (id) on delete set null,
  published_at timestamptz not null default now(),
  unique (survey_id, version)
);

alter table public.surveys
  add constraint surveys_current_version_fkey foreign key (current_version_id) references public.survey_versions (id);

create table public.survey_links (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations (id) on delete cascade,
  survey_id uuid not null references public.surveys (id) on delete cascade,
  location_id uuid not null references public.locations (id) on delete cascade,
  -- Short random code in the public URL (/s/{code}); never an internal id.
  public_code text not null unique check (public_code ~ '^[A-Za-z0-9]{8,16}$'),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (survey_id, location_id)
);

create index survey_links_organization_id_idx on public.survey_links (organization_id);

create table public.survey_responses (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations (id) on delete cascade,
  survey_id uuid not null references public.surveys (id) on delete cascade,
  survey_version_id uuid not null references public.survey_versions (id),
  location_id uuid not null references public.locations (id),
  link_id uuid references public.survey_links (id) on delete set null,
  -- Generated by the customer's browser; makes retries and double taps idempotent.
  submission_id uuid not null unique,
  locale public.app_locale not null,
  device_type text check (device_type in ('mobile', 'tablet', 'desktop')),
  -- Copied from the answers at submission so dashboards aggregate one table.
  csat_score smallint check (csat_score between 1 and 5),
  nps_score smallint check (nps_score between 0 and 10),
  has_comment boolean not null default false,
  submitted_at timestamptz not null default now()
);

create index survey_responses_org_submitted_idx on public.survey_responses (organization_id, submitted_at desc);
create index survey_responses_survey_submitted_idx on public.survey_responses (survey_id, submitted_at desc);
create index survey_responses_location_submitted_idx on public.survey_responses (location_id, submitted_at desc);

create table public.survey_answers (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations (id) on delete cascade,
  response_id uuid not null references public.survey_responses (id) on delete cascade,
  question_id uuid not null,
  value_number smallint check (value_number between 0 and 10),
  value_text text check (char_length(value_text) <= 1000),
  value_option_ids uuid[],
  unique (response_id, question_id)
);

create index survey_answers_question_id_idx on public.survey_answers (question_id);

create trigger surveys_set_updated_at before update on public.surveys
for each row execute function private.set_updated_at();
create trigger survey_links_set_updated_at before update on public.survey_links
for each row execute function private.set_updated_at();

-- Editing the draft of a published survey marks it as having unpublished changes.
create function private.mark_unpublished_changes()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if new.current_version_id is not distinct from old.current_version_id
     and (new.questions, new.thank_you, new.locales, new.default_locale)
         is distinct from (old.questions, old.thank_you, old.locales, old.default_locale)
     and new.current_version_id is not null
  then
    new.has_unpublished_changes := true;
  end if;
  return new;
end;
$$;

create trigger surveys_mark_unpublished_changes before update on public.surveys
for each row execute function private.mark_unpublished_changes();

-- A link must point to a survey and a location of the same organization.
create function private.check_link_tenant()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not exists (select 1 from public.surveys where id = new.survey_id and organization_id = new.organization_id)
     or not exists (select 1 from public.locations where id = new.location_id and organization_id = new.organization_id)
  then
    raise exception 'forbidden' using errcode = 'P0001';
  end if;
  return new;
end;
$$;

create trigger survey_links_check_tenant before insert or update of organization_id, survey_id, location_id
on public.survey_links for each row execute function private.check_link_tenant();

-- Draft edits aren't audited (too frequent); creation, renames, status changes and publishing are.
create trigger surveys_audit after insert or update of name, status, current_version_id on public.surveys
for each row execute function private.write_audit();
create trigger survey_links_audit after insert or update on public.survey_links
for each row execute function private.write_audit();

-- ───────── Row Level Security ─────────

alter table public.surveys enable row level security;
alter table public.survey_versions enable row level security;
alter table public.survey_links enable row level security;
alter table public.survey_responses enable row level security;
alter table public.survey_answers enable row level security;

revoke all on public.surveys, public.survey_versions, public.survey_links, public.survey_responses, public.survey_answers
from anon, authenticated;

create policy "Members can read surveys" on public.surveys
for select to authenticated using ((select private.is_member(organization_id)));
create policy "Managers can create surveys" on public.surveys
for insert to authenticated with check ((select private.has_role(organization_id, 'manager')));
create policy "Managers can edit surveys" on public.surveys
for update to authenticated
using ((select private.has_role(organization_id, 'manager')))
with check ((select private.has_role(organization_id, 'manager')));
grant select on public.surveys to authenticated;
grant insert (organization_id, name, default_locale, locales, questions, thank_you) on public.surveys to authenticated;
-- Status and versions change only through publish_survey / set_survey_status.
grant update (name, default_locale, locales, questions, thank_you) on public.surveys to authenticated;

create policy "Members can read survey versions" on public.survey_versions
for select to authenticated using ((select private.is_member(organization_id)));
grant select on public.survey_versions to authenticated;

create policy "Members can read survey links" on public.survey_links
for select to authenticated using ((select private.is_member(organization_id)));
create policy "Managers can create survey links" on public.survey_links
for insert to authenticated with check ((select private.has_role(organization_id, 'manager')));
create policy "Managers can turn survey links on and off" on public.survey_links
for update to authenticated
using ((select private.has_role(organization_id, 'manager')))
with check ((select private.has_role(organization_id, 'manager')));
grant select on public.survey_links to authenticated;
grant insert (organization_id, survey_id, location_id, public_code) on public.survey_links to authenticated;
grant update (is_active) on public.survey_links to authenticated;

-- Responses are written only by submit_survey_response (server); every member can read them.
create policy "Members can read responses" on public.survey_responses
for select to authenticated using ((select private.is_member(organization_id)));
grant select on public.survey_responses to authenticated;
create policy "Members can read answers" on public.survey_answers
for select to authenticated using ((select private.is_member(organization_id)));
grant select on public.survey_answers to authenticated;

-- ───────── Functions ─────────

-- Freezes the current draft into a new version and makes it live. Managers and above.
create function public.publish_survey(p_survey_id uuid)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  survey public.surveys;
  next_version integer;
  version_id uuid;
begin
  select * into survey from public.surveys where id = p_survey_id for update;
  if not found then raise exception 'not_found' using errcode = 'P0001'; end if;
  if not private.has_role(survey.organization_id, 'manager') then
    raise exception 'forbidden' using errcode = 'P0001';
  end if;
  if survey.status = 'archived' then raise exception 'forbidden' using errcode = 'P0001'; end if;
  if jsonb_array_length(survey.questions) not between 1 and 10 then
    raise exception 'invalid_survey' using errcode = 'P0001';
  end if;

  select coalesce(max(version), 0) + 1 into next_version from public.survey_versions where survey_id = p_survey_id;

  insert into public.survey_versions (organization_id, survey_id, version, definition, published_by)
  values (
    survey.organization_id, p_survey_id, next_version,
    jsonb_build_object(
      'questions', survey.questions,
      'thankYou', survey.thank_you,
      'locales', to_jsonb(survey.locales),
      'defaultLocale', survey.default_locale
    ),
    (select auth.uid())
  )
  returning id into version_id;

  update public.surveys
  set current_version_id = version_id, status = 'published', has_unpublished_changes = false
  where id = p_survey_id;
  return version_id;
end;
$$;

-- Pause, resume or archive. Resuming requires a published version.
create function public.set_survey_status(p_survey_id uuid, p_status public.survey_status)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  survey public.surveys;
begin
  select * into survey from public.surveys where id = p_survey_id for update;
  if not found then raise exception 'not_found' using errcode = 'P0001'; end if;
  if not private.has_role(survey.organization_id, 'manager') then
    raise exception 'forbidden' using errcode = 'P0001';
  end if;
  if p_status = 'draft' or (p_status = 'published' and survey.current_version_id is null) then
    raise exception 'invalid_survey' using errcode = 'P0001';
  end if;
  update public.surveys set status = p_status where id = p_survey_id;
end;
$$;

-- What a customer sees at /s/{code}. Callable by anyone; returns nothing unless the link,
-- survey and location are all live. Exposes only what the survey page needs.
create function public.get_public_survey(p_code text)
returns jsonb
language sql
stable
security definer
set search_path = ''
as $$
  select jsonb_build_object(
    'linkId', l.id,
    'organizationName', o.name,
    'locationName', loc.name,
    'versionId', v.id,
    'definition', v.definition
  )
  from public.survey_links l
  join public.surveys s on s.id = l.survey_id
  join public.survey_versions v on v.id = s.current_version_id
  join public.organizations o on o.id = l.organization_id
  join public.locations loc on loc.id = l.location_id
  where l.public_code = p_code
    and l.is_active
    and s.status = 'published'
    and loc.archived_at is null
$$;

-- Records a customer's answers. Called only by the server (service role) after rate limiting,
-- never directly by browsers. Validates every answer against the published version.
create function public.submit_survey_response(
  p_code text,
  p_version_id uuid,
  p_submission_id uuid,
  p_locale public.app_locale,
  p_answers jsonb,
  p_device_type text
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  link public.survey_links;
  survey public.surveys;
  definition jsonb;
  question jsonb;
  answer jsonb;
  question_ids text[] := '{}';
  option_ids text[];
  chosen text[];
  number_value integer;
  text_value text;
  csat smallint;
  nps smallint;
  comment boolean := false;
  response_id uuid;
begin
  select id into response_id from public.survey_responses where submission_id = p_submission_id;
  if found then return response_id; end if;

  select * into link from public.survey_links where public_code = p_code and is_active;
  if not found then raise exception 'survey_unavailable' using errcode = 'P0001'; end if;
  select * into survey from public.surveys where id = link.survey_id;
  if survey.status <> 'published'
     or exists (select 1 from public.locations where id = link.location_id and archived_at is not null) then
    raise exception 'survey_unavailable' using errcode = 'P0001';
  end if;
  -- The survey was republished while the customer was answering.
  if survey.current_version_id <> p_version_id then
    raise exception 'survey_changed' using errcode = 'P0001';
  end if;
  select v.definition into definition from public.survey_versions v where v.id = survey.current_version_id;
  if not (p_locale::text in (select jsonb_array_elements_text(definition -> 'locales'))) then
    raise exception 'invalid_answer' using errcode = 'P0001';
  end if;
  if jsonb_typeof(p_answers) <> 'object' then raise exception 'invalid_answer' using errcode = 'P0001'; end if;

  insert into public.survey_responses (organization_id, survey_id, survey_version_id, location_id, link_id, submission_id, locale, device_type)
  values (link.organization_id, link.survey_id, survey.current_version_id, link.location_id, link.id, p_submission_id, p_locale,
          case when p_device_type in ('mobile', 'tablet', 'desktop') then p_device_type end)
  returning id into response_id;

  for question in select * from jsonb_array_elements(definition -> 'questions') loop
    question_ids := question_ids || (question ->> 'id');
    answer := p_answers -> (question ->> 'id');
    if answer is null or answer = 'null'::jsonb then
      if (question ->> 'required')::boolean then raise exception 'missing_answer' using errcode = 'P0001'; end if;
      continue;
    end if;

    case question ->> 'type'
      when 'rating', 'nps' then
        if jsonb_typeof(answer -> 'number') <> 'number' then raise exception 'invalid_answer' using errcode = 'P0001'; end if;
        number_value := (answer ->> 'number')::numeric;
        if number_value::numeric <> (answer ->> 'number')::numeric
           or (question ->> 'type' = 'rating' and number_value not between 1 and 5)
           or (question ->> 'type' = 'nps' and number_value not between 0 and 10) then
          raise exception 'invalid_answer' using errcode = 'P0001';
        end if;
        insert into public.survey_answers (organization_id, response_id, question_id, value_number)
        values (link.organization_id, response_id, (question ->> 'id')::uuid, number_value);
        if question ->> 'type' = 'rating' and csat is null and coalesce(question ->> 'role', '') = 'csat' then csat := number_value; end if;
        if question ->> 'type' = 'nps' and nps is null then nps := number_value; end if;

      when 'single_choice', 'multiple_choice' then
        if jsonb_typeof(answer -> 'options') <> 'array' then raise exception 'invalid_answer' using errcode = 'P0001'; end if;
        select array_agg(o ->> 'id') into option_ids from jsonb_array_elements(question -> 'options') o;
        select array_agg(distinct c) into chosen from jsonb_array_elements_text(answer -> 'options') c;
        if chosen is null
           or not (chosen <@ option_ids)
           or cardinality(chosen) <> jsonb_array_length(answer -> 'options')
           or (question ->> 'type' = 'single_choice' and cardinality(chosen) <> 1) then
          raise exception 'invalid_answer' using errcode = 'P0001';
        end if;
        insert into public.survey_answers (organization_id, response_id, question_id, value_option_ids)
        values (link.organization_id, response_id, (question ->> 'id')::uuid, chosen::uuid[]);

      when 'text' then
        text_value := btrim(answer ->> 'text');
        if text_value is null or text_value = '' then
          if (question ->> 'required')::boolean then raise exception 'missing_answer' using errcode = 'P0001'; end if;
          continue;
        end if;
        if char_length(text_value) > 1000 then raise exception 'invalid_answer' using errcode = 'P0001'; end if;
        insert into public.survey_answers (organization_id, response_id, question_id, value_text)
        values (link.organization_id, response_id, (question ->> 'id')::uuid, text_value);
        comment := true;

      else
        raise exception 'invalid_answer' using errcode = 'P0001';
    end case;
  end loop;

  -- Answers to questions that aren't in this version are rejected.
  if exists (select 1 from jsonb_object_keys(p_answers) k where not (k = any (question_ids))) then
    raise exception 'invalid_answer' using errcode = 'P0001';
  end if;

  update public.survey_responses set csat_score = csat, nps_score = nps, has_comment = comment where id = response_id;
  return response_id;
end;
$$;

revoke execute on function
  public.publish_survey(uuid),
  public.set_survey_status(uuid, public.survey_status),
  public.get_public_survey(text),
  public.submit_survey_response(text, uuid, uuid, public.app_locale, jsonb, text)
from public, anon, authenticated;

grant execute on function public.publish_survey(uuid), public.set_survey_status(uuid, public.survey_status) to authenticated;
grant execute on function public.get_public_survey(text) to anon, authenticated;
grant execute on function public.submit_survey_response(text, uuid, uuid, public.app_locale, jsonb, text) to service_role;
